[app]
app1 ansible_host=192.168.1.207 ansible_user=v1
app2 ansible_host=192.168.1.206 ansible_user=v2

[loadbalancer]
lb ansible_host=192.168.1.208 ansible_user=v4

[cache] 
cache1 ansible_host=192.168.1.209 ansible_user=v5

[monitoring]
monitor ansible_host=192.168.1.205 ansible_user=v3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become_pass=test123
